# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveller',
            name='terms',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
