# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_traveller_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveller',
            name='current_location',
            field=models.CharField(default='Toronto', max_length=200),
            preserve_default=False,
        ),
    ]
