# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_traveller_current_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=50)),
                ('body_text', models.TextField(blank=True, null=True)),
                ('logo_image', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.AlterField(
            model_name='traveller',
            name='current_location',
            field=models.CharField(blank=True, help_text='You can leave this blank', max_length=200),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='terms',
            field=models.BooleanField(help_text='I agree to the terms and conditions.'),
        ),
    ]
