# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_traveller_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
