# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20160621_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='image',
            field=models.ImageField(blank=True, default='images/feet.png', max_length=10000, null=True, upload_to=None),
        ),
    ]
