# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20160621_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('body_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
